package model.ERP.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 08 13:56:53 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblSuppOpenBlncImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SuppOpenBlncId,
        SuppOpenBlncDated,
        PblSuppId,
        SuppOpenBlncDr,
        SuppOpenBlncCr,
        GroupCompanyId,
        CompanySbuId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SUPPOPENBLNCID = AttributesEnum.SuppOpenBlncId.index();
    public static final int SUPPOPENBLNCDATED = AttributesEnum.SuppOpenBlncDated.index();
    public static final int PBLSUPPID = AttributesEnum.PblSuppId.index();
    public static final int SUPPOPENBLNCDR = AttributesEnum.SuppOpenBlncDr.index();
    public static final int SUPPOPENBLNCCR = AttributesEnum.SuppOpenBlncCr.index();
    public static final int GROUPCOMPANYID = AttributesEnum.GroupCompanyId.index();
    public static final int COMPANYSBUID = AttributesEnum.CompanySbuId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblSuppOpenBlncImpl() {
    }

    /**
     * Gets the attribute value for SuppOpenBlncId, using the alias name SuppOpenBlncId.
     * @return the value of SuppOpenBlncId
     */
    public BigDecimal getSuppOpenBlncId() {
        return (BigDecimal) getAttributeInternal(SUPPOPENBLNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppOpenBlncId.
     * @param value value to set the SuppOpenBlncId
     */
    public void setSuppOpenBlncId(BigDecimal value) {
        setAttributeInternal(SUPPOPENBLNCID, value);
    }

    /**
     * Gets the attribute value for SuppOpenBlncDated, using the alias name SuppOpenBlncDated.
     * @return the value of SuppOpenBlncDated
     */
    public Timestamp getSuppOpenBlncDated() {
        return (Timestamp) getAttributeInternal(SUPPOPENBLNCDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppOpenBlncDated.
     * @param value value to set the SuppOpenBlncDated
     */
    public void setSuppOpenBlncDated(Timestamp value) {
        setAttributeInternal(SUPPOPENBLNCDATED, value);
    }

    /**
     * Gets the attribute value for PblSuppId, using the alias name PblSuppId.
     * @return the value of PblSuppId
     */
    public BigDecimal getPblSuppId() {
        return (BigDecimal) getAttributeInternal(PBLSUPPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PblSuppId.
     * @param value value to set the PblSuppId
     */
    public void setPblSuppId(BigDecimal value) {
        setAttributeInternal(PBLSUPPID, value);
    }

    /**
     * Gets the attribute value for SuppOpenBlncDr, using the alias name SuppOpenBlncDr.
     * @return the value of SuppOpenBlncDr
     */
    public BigDecimal getSuppOpenBlncDr() {
        return (BigDecimal) getAttributeInternal(SUPPOPENBLNCDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppOpenBlncDr.
     * @param value value to set the SuppOpenBlncDr
     */
    public void setSuppOpenBlncDr(BigDecimal value) {
        setAttributeInternal(SUPPOPENBLNCDR, value);
    }

    /**
     * Gets the attribute value for SuppOpenBlncCr, using the alias name SuppOpenBlncCr.
     * @return the value of SuppOpenBlncCr
     */
    public BigDecimal getSuppOpenBlncCr() {
        return (BigDecimal) getAttributeInternal(SUPPOPENBLNCCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppOpenBlncCr.
     * @param value value to set the SuppOpenBlncCr
     */
    public void setSuppOpenBlncCr(BigDecimal value) {
        setAttributeInternal(SUPPOPENBLNCCR, value);
    }

    /**
     * Gets the attribute value for GroupCompanyId, using the alias name GroupCompanyId.
     * @return the value of GroupCompanyId
     */
    public Number getGroupCompanyId() {
        return (Number) getAttributeInternal(GROUPCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupCompanyId.
     * @param value value to set the GroupCompanyId
     */
    public void setGroupCompanyId(Number value) {
        setAttributeInternal(GROUPCOMPANYID, value);
    }

    /**
     * Gets the attribute value for CompanySbuId, using the alias name CompanySbuId.
     * @return the value of CompanySbuId
     */
    public Number getCompanySbuId() {
        return (Number) getAttributeInternal(COMPANYSBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanySbuId.
     * @param value value to set the CompanySbuId
     */
    public void setCompanySbuId(Number value) {
        setAttributeInternal(COMPANYSBUID, value);
    }

    /**
     * @param suppOpenBlncId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal suppOpenBlncId) {
        return new Key(new Object[] { suppOpenBlncId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.ERP.EO.TblSuppOpenBlnc");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number cmpnyId = null;
                Number sbuId = null;
                 try {
                   
                     cmpnyId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessCmpnyID"));
                     sbuId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessSBUID"));
                 } catch(Exception ex) {
                     ex.printStackTrace();
                 }
                 
                 if (operation == DML_INSERT) {

                     setGroupCompanyId(cmpnyId);
                     setCompanySbuId(sbuId);

                     } else if(operation == DML_UPDATE) {
                     
                     setGroupCompanyId(cmpnyId);
                     setCompanySbuId(sbuId);
                     
                   
                 }

        super.doDML(operation, e);
    }
}

